glibc: make sure the system has lunar v42 or later

diff --git a/libs/glibc/PRE_BUILD b/libs/glibc/PRE_BUILD
--- a/libs/glibc/PRE_BUILD
+++ b/libs/glibc/PRE_BUILD
@@ -3,6 +3,12 @@ default_pre_build &&
 # Keeping this temporary, it's a bad hack, we need to change how we define our compiler flags
 sedit 's@^#\s*warning \+_FORTIFY_SOURCE requires compiling with optimization.*$@/* Disabled by lunar as there is no better solution: \0*/@' include/features.h &&
 
+# Requires lunar v42 or later
+if [[ $(installed_version lunar) < 42 ]]; then
+  message "${PROBLEM_COLOR}ERROR: ${MESSAGE_COLOR}Please update the 'lunar' module, v42 or later is required to upgrade glibc.${DEFAULT_COLOR}"
+  exit 1
+fi
+
 # Pre flight check for glibc upgrade
 while read line path; do
   if [[ "$path" == "/lib" ]]; then
@@ -22,7 +28,7 @@ cat <<EOF
 
 /lib
 /usr/lib
-/etc/ld.so.conf.d/*.conf
+include /etc/ld.so.conf.d/*.conf
 
 EOF
     exit 1
